---
title: "Create data set for analysis"
output: html_notebook
---

```{r}
library(tidyverse)
```


Selected cell lines

```{r}
selected_cell_lines_for_SOX10 <- here::here("class_4_linear_regression/depmap/selected_cell_lines_for_SOX10.csv") %>% 
  read_csv()
```


```{r}
expresison_data <- here::here("class_4_linear_regression/depmap/OmicsExpressionProteinCodingGenesTPMLogp1.csv") %>% read_csv()
```

I want to subset to 

```{r}
expression_data_selected <- expresison_data %>% 
  dplyr::filter(...1 %in% colnames(selected_cell_lines_for_SOX10)) %>% 
  dplyr::rename(depmap_id = ...1)
```

Data set for prediction 

```{r}
tailored_data_for_prediction <- expression_data_selected %>%
  # Select columns containing "SOX10"
  select(matches("SOX10")) %>%
  # Bind with 20 randomly selected other columns
  bind_cols(
    expression_data_selected %>% 
      select(-matches("SOX10")) %>% 
      select(sample(names(.), 20))
  ) %>%
  # Add the depmap_id column if it wasn't selected
  bind_cols(expression_data_selected %>% select(depmap_id)) %>%
  # Randomly sample 100 rows (or all rows if less than 100)
  slice_sample(n = min(100, nrow(.)))
```

```{r}
Chronos_score <- here::here("class_4_linear_regression/depmap/SOX10 CRISPR (DepMap Public 24Q2+Score Chronos).csv") %>% 
  read_csv() %>% 
  janitor::clean_names()
```
```{r}
tailored_data_for_ML_dataset <- tailored_data_for_prediction %>% dplyr::left_join(Chronos_score, by = "depmap_id") %>% 
  dplyr::select(-expression_public_24q2) %>% 
  janitor::remove_constant()
```


```{r}
tailored_data_for_ML_dataset %>% 
  ggplot(aes(y=`SOX10 (6663)`, x = crispr_dep_map_public_24q2_score_chronos))+
  geom_point() +
  labs(title = "Relationship Expression as a function of chronos score for SOX10")
```

```{r}
tailored_data_for_ML_dataset %>% write_csv(here::here("class_4_linear_regression/depmap/dependency_score_to_predict.csv"))
```
